name: task-1-kata
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  pull_request:
    paths:
      - '**.ts'
jobs:
  LearnGitHubActions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: |
          ls
          echo "Branch = ${{ github.ref_name }}"
          echo "Commit = ${{ github.sha }}"
          cd desktop-app
          npm ci
          npm test
          npm run e2e